### ISSUE TITLE
集成iLiveSDK的工程无法运行

### ISSUE THREAD

**Issue by gustplus** [zhaoyang21cn/iLiveSDK_PC_Suixinbo#1]
您好，我按照您Demo里的步骤配置了自己的代码工程，编译通过但运行时出现“应用程序无法正常启动（0xc000007b）”，请问您是否知道问题出在哪里？

编译机器：win10 x64
vs版本：vs2012
* 由于您的demo中的ilivesdk与官网提供的下载不同（官网缺少ilivesdk.lib相关），故使用demo中的版本

期望得到您的回复！

**Comment by jepsonyang** [comment]
打开随心播项目后，默认启动项目时LiveSDK，它是一个静态库，所以无法运行，解决方法: 
在suixinbo_Qt项目上鼠标右键-->设为启动项目，然后再编译运行；（注意：需要安装Qt环境，可参考https://github.com/zhaoyang21cn/iLiveSDK_PC_Demos/blob/master/doc/suixinbo_README.md）

**Comment by gustplus** [comment]
您好，感谢回复。“应用程序无法正常启动（0xc000007b）”的运行错误是在我**新建的项目**运行时出现的，项目的配置完全遵循官网上[PC端集成](https://www.qcloud.com/document/product/268/7672) 中”四 集成iLive SDK到开发者自己的代码工程里”的步骤。
再次感谢

**Comment by jepsonyang** [comment]
可以加下技术交流群，594923937，有问题可以在群里反馈下
