### ISSUE TITLE
iLiveSDK 接入到webrtc-room支持吗？

### ISSUE THREAD

**Issue by zhangtianren** [zhaoyang21cn/iLiveSDK_PC_Suixinbo#4]
移动直播能够在参数里设置房间列表的服务端地址，随心播不支持呀？

PC端如何与小程序互通呢？

**Comment by cddjr** [comment]
说是要给50万定制费或者弃用互动直播sdk  :)

**Comment by RayGyoe** [comment]
直接可以通，我已经切换了

**Comment by zhangtianren** [comment]
可以通啦，说是tx有两套环境，官方接口没有说明。

保证两段在同一套环境上就能通（小程序虚拟机不能跑的哦）
